version: '3'
services:
  gitea:
    image: gitea/gitea:1.15.6
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - gitea-db
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: gitea-db
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: giteapw
      REDMINE_DB_ENCODING: utf8mb4
      TZ: Asia/Tokyo
  gitea-db:
    build:
      context: ./db/docker
      dockerfile: Dockerfile
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: giteapassword
      MYSQL_USER: gitea
      MYSQL_PASSWORD: giteapw
      MYSQL_DATABASE: gitea
      TZ: Asia/Tokyo
    volumes:
      - ./db/dbdata:/var/lib/mysql
    user: "1000:1000"
