version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.33.2
    hostname: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus/data:/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    user: root

  # node-exporter:
  #   image: prom/node-exporter:v1.3.1
  #   ports:
  #     - "9100:9100"

  grafana:
    image: grafana/grafana:8.3.6
    hostname: grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    user: root
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_PROTOCOL=http

