version: '3'
services:
  jenkins-dood-master:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: tcp://192.168.0.128:2375   ## Docker が動いているホストのIP
      TZ: Asia/Tokyo
      JAVA_OPTS: -Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8


