global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - prometheus:9090
        # - node-exporter:9100
        # - 192.168.0.128:9182
  # - job_name: 'linux-node'
  #   static_configs:
  #     - targets:
  #       - 192.168.0.1:9100
  # - job_name: 'windows-node'
  #   static_configs:
  #     - targets:
  #       - 192.168.0.1:9182
