version: "3"
services:
  vue_app:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
      - /workspace/node_modules
    tty: true
